version: 2
jobs:
  install-job:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/backbone-learn
    steps:
      - checkout

      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/backbone-learn
          paths:
            - node_modules/*

  test-job:
    docker:
      - image: circleci/node:10.14

    working_directory: ~/react-robust-ui

    steps:
      - checkout
      - attach_workspace:
          at: ~/backbone-learn
      - run: npm test

  lint-job:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/backbone-learn

    steps:
      - checkout
      - attach_workspace:
          at: ~/backbone-learn
      - run: npm run lint

  build-job:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/backbone-learn

    steps:
      - checkout
      - attach_workspace:
          at: ~/backbone-learn
      - run: npm run build
      - persist_to_workspace:
          root: ~/backbone-learn
          paths:
            - dist/*

  size-job:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/backbone-learn

    steps:
      - checkout
      - attach_workspace:
          at: ~/backbone-learn
      - run: npm run size

  deployment-job:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/backbone-learn

    steps:
      - checkout
      - attach_workspace:
          at: ~/backbone-learn
      - run: npm run surge --project ./dist --domain redtn-backbone-learn.surge.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - install-job
      - build-job:
          requires:
            - install-job
      - test-job:
          requires:
            - install-job
      - lint-job:
          requires:
            - install-job
      - size-job:
          requires:
            - build-job
      - deployment-job:
          requires:
            - build-job
          filters:
            branches:
              only: master